### ISSUE TITLE
ELIFECYCLE errno 1 when running npm run test:axe

### ISSUE THREAD

**Issue by rianrietveld** [wpaccessibility/wp-theme-auditor#12]
At the contributor day of WordCmap London we (@Netzberufler @GaryJones @rianrietveld) tested the auditor.

Test environment:
Local site http://one.wordpress.test/ running on VVV
Node: v10.15.1
Npm: 6.9.0
Installed the [a11y-theme-unit-test](https://github.com/wpaccessibility/a11y-theme-unit-test)
Used the twentynineteen theme

Followed the install instructions like in the readme.

We run into the following issue while running `npm run test:axe`:
The tests are run, relevant axe data is shown in the terminal but at the end the script crashes:
```
Test Suites: 53 failed, 53 total
Tests:       53 failed, 53 total
Snapshots:   0 total
Time:        78.189s
Ran all test suites.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! twentynineteen@1.0.0 test:axe: `npx wp-scripts test-e2e`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the twentynineteen@1.0.0 test:axe script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/rianrietveld/.npm/_logs/2019-04-05T11_54_33_198Z-debug.log
```
 And in the /Users/rianrietveld/.npm/_logs/2019-04-05T11_54_33_198Z-debug.log
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'test:axe' ]
2 info using npm@6.9.0
3 info using node@v10.15.1
4 verbose run-script [ 'pretest:axe', 'test:axe', 'posttest:axe' ]
5 info lifecycle twentynineteen@1.0.0~pretest:axe: twentynineteen@1.0.0
6 info lifecycle twentynineteen@1.0.0~test:axe: twentynineteen@1.0.0
7 verbose lifecycle twentynineteen@1.0.0~test:axe: unsafe-perm in lifecycle true
8 verbose lifecycle twentynineteen@1.0.0~test:axe: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/$
9 verbose lifecycle twentynineteen@1.0.0~test:axe: CWD: /Users/rianrietveld/vagrant-local/www/wordpress-one/public_html/wp-content$
10 silly lifecycle twentynineteen@1.0.0~test:axe: Args: [ '-c', 'wp-scripts test-e2e' ]
11 silly lifecycle twentynineteen@1.0.0~test:axe: Returned: code: 1  signal: null
12 info lifecycle twentynineteen@1.0.0~test:axe: Failed to exec test:axe script
13 verbose stack Error: twentynineteen@1.0.0 test:axe: `wp-scripts test-e2e`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:189:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:189:13)
13 verbose stack     at maybeClose (internal/child_process.js:970:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid twentynineteen@1.0.0
15 verbose cwd /Users/rianrietveld/vagrant-local/www/wordpress-one/public_html/wp-content/themes/twentynineteen
16 verbose Darwin 18.5.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "test:axe"
18 verbose node v10.15.1
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 1
22 error twentynineteen@1.0.0 test:axe: `wp-scripts test-e2e`
22 error Exit status 1
23 error Failed at the twentynineteen@1.0.0 test:axe script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

```
Running the same with sudo gives the same result.

**Comment by greatislander** [comment]
I could be mistaken but I think this is the expected behavior running this kind of test? See: https://github.com/facebook/jest/issues/7803

Perhaps @gziolo has more insight on how Jest tests exit on pass/fail…

**Comment by gziolo** [comment]
> I could be mistaken but I think this is the expected behavior running this kind of test? See: [facebook/jest#7803](https://github.com/facebook/jest/issues/7803)
> 
> Perhaps @gziolo has more insight on how Jest tests exit on pass/fail…

Yes, it's correct. It exits with 0 when all tests pass, and it exists with 1 when any of the tests fail. It is usual behavior for most of the Node-based CLI tools.

**Comment by rianrietveld** [comment]
Maybe I miss some documentation then, but how do we see the errors? Only with what passes by in the terminal output?
Is it possible to generate a json file with the errors/warning when you run the script?
Or another way to display the errors in a human friendly way?
Now the script ends like an runtime error, without any feedback on what is wrong.

**Comment by greatislander** [comment]
@rianrietveld You're right; currently the only way to view the errors is to scroll back through the terminal output, which is less than ideal. I think generating a report file would be a major improvement and I'll add a ticket to explore this.

**Comment by greatislander** [comment]
I'm going to close this in favour of https://github.com/wpaccessibility/wp-theme-auditor/issues/13. I think generating a report file makes sense.
