### ISSUE TITLE
Any plans to bring this tool to non-local environments?

### ISSUE THREAD

**Issue by bozzmedia** [wpaccessibility/wp-theme-auditor#2]
Seems like a really great tool, any thoughts on bringing this to a plugin to use with WP sites already deployed to a server? Thanks!

**Comment by greatislander** [comment]
Hi @bozzmedia, you can use it for non-local environments by passing a different base URL and writing some test cases for your specific site. For example, if you ran this:

```bash
WP_BASE_URL=https://wordpress.org npm run test:axe
```

It would run any available test cases against https://wordpress.org.

There are plans to add support for running these tests in CI environments as well.

**Comment by bozzmedia** [comment]
Awesome, I'll give that a try. Thanks!
