### ISSUE TITLE
npm install fails to create bin/postinstall.js file

### ISSUE THREAD

**Issue by ville6000** [wpaccessibility/wp-theme-auditor#24]
npm install fails to create bin/postinstall.js file. I'm using npm version 6.9.0

If the bin/postinstall.js file is run from node modules `node node_modules/wp-theme-auditor/bin/postinstall.js` it creates an folder named 'undefined'.

**Comment by greatislander** [comment]
Thanks for reporting this, @ville6000. I've just finished setting up a new method for adding `wp-theme-auditor` to a project. See #5. You should now be able to add `wp-theme-auditor` to your theme by running: 

```bash
$ npm init wp-theme-auditor
```
