### ISSUE TITLE
Typo in README.md

### ISSUE THREAD

**Issue by rianrietveld** [wpaccessibility/wp-theme-auditor#9]
The text
Then you'll need to add more test cases. You can do this interactively by running `npm run create-test-case` from your theme's root directory.

Should be
Then you'll need to add more test cases. You can do this interactively by running `npm run create-test-cases` from your theme's root directory.

With an s added to the case :-)

**Comment by greatislander** [comment]
Thanks for catching that, @rianrietveld!

**Comment by samikeijonen** [comment]
And I love that there was typo in the title!!
